@echo off
@PATH C:\WATCOM\BINNT64;C:\WATCOM\BINNT;%PATH%
@SET INCLUDE=C:\WATCOM\H;C:\WATCOM\H\NT;C:\WATCOM\H\NT\DIRECTX;C:\WATCOM\H\NT\DDK;%INCLUDE%
@SET WATCOM=C:\WATCOM
@SET EDPATH=C:\WATCOM\EDDAT
@SET WHTMLHELP=C:\WATCOM\BINNT\HELP
@SET WIPFC=C:\WATCOM\WIPFC
set NWSDK=C:\NWSDK\merge
set NOVELLNDK=C:\NWSDK\novell-nwsdkc-devel-2008.03.05-1netware_windows\libc
set INCLUDE=%NWSDK%\include;%NWSDK%\include\nlm;%INCLUDE%
set LIB=C:\WATCOM\lib386;C:\WATCOM\lib386\netware;%NWSDK%\imports;
set PATH=C:\WATCOM\binnt;%PATH%

wcc386 -bt=netware -zp4 -5s SMP-IDLE.c
wlink @SMP-IDLE.lnkr